name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/*.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Sync latest Unblocked Music source code
        run: |
          # 1. Clone repo (shallow)
          git clone --depth=1 https://github.com/UnblockNeteaseMusic/server.git
          
          # 2. Selective zip (exclude dev files)
          cd server && \
          zip -r ../UnblockNeteaseMusic.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x ".vscode/*" \
            -x ".yarn/*" && \
          cd .. && \
          
          # 3. Clean old and move new
          rm -f ./app/src/main/assets/UnblockNeteaseMusic.zip && \
          mv ./UnblockNeteaseMusic.zip ./app/src/main/assets/
          
          # 4. Cleanup
          rm -rf server

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew app:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{github.workspace}}/app/build/outputs/apk/release/*.apk
          if-no-files-found: warn
          retention-days: 30
